/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface KButton {
    'color': "plain" | "primary" | "secondary" | "danger";
    'size': "sm" | "md" | "lg" | "xl";
    'type': "basic" | "raised" | "outline" | "flat";
  }
  interface KButtonAttributes extends StencilHTMLAttributes {
    'color'?: "plain" | "primary" | "secondary" | "danger";
    'size'?: "sm" | "md" | "lg" | "xl";
    'type'?: "basic" | "raised" | "outline" | "flat";
  }

  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface MyComponentAttributes extends StencilHTMLAttributes {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'KButton': Components.KButton;
    'MyComponent': Components.MyComponent;
  }

  interface StencilIntrinsicElements {
    'k-button': Components.KButtonAttributes;
    'my-component': Components.MyComponentAttributes;
  }


  interface HTMLKButtonElement extends Components.KButton, HTMLStencilElement {}
  var HTMLKButtonElement: {
    prototype: HTMLKButtonElement;
    new (): HTMLKButtonElement;
  };

  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLElementTagNameMap {
    'k-button': HTMLKButtonElement
    'my-component': HTMLMyComponentElement
  }

  interface ElementTagNameMap {
    'k-button': HTMLKButtonElement;
    'my-component': HTMLMyComponentElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
